import { NextResponse } from "next/server";
import packageJson from "../../../../package.json";

export async function GET() {
  return NextResponse.json({
    id: "ye-cinema",
    name: "Cinema",
    version: packageJson.version,
    description: "Personal movie & TV discovery with watchlists, ratings, and reviews",
    icon: "Film",
    accent_color: "#a855f7",
    permissions: ["timeline:write", "widgets:register"],
  surfaceSchemaVersion: 1,
    surfaces: [
    {
      id: "app-settings",
      kind: "settings-panel",
      placement: "app-settings",
      name: "App Settings",
      description: "App-owned settings panel",
      embedPath: "/embed/settings",
      permissions: [],
    },
      {
        id: "now-watching",
        kind: "widget",
        placement: "dashboard",
        name: "Now Watching",
        description: "Currently watching and recently watched movies & shows",
        embedPath: "/embed/widget/now-watching",
        permissions: [],
        defaultSize: { width: 28, height: 25 },
        minSize: { width: 20, height: 18 },
        maxSize: { width: 50, height: 45 },
        refreshInterval: 300,
      },
      {
        id: "trending",
        kind: "widget",
        placement: "dashboard",
        name: "Trending Movies",
        description: "Today's trending movies from TMDB",
        embedPath: "/embed/widget/trending",
        permissions: [],
        defaultSize: { width: 35, height: 28 },
        minSize: { width: 25, height: 20 },
        maxSize: { width: 55, height: 50 },
        refreshInterval: 3600,
      },
      {
        id: "movie-info",
        kind: "info-card",
        placement: "timeline",
        name: "Movie info",
        description: "Movie and TV show details with ratings",
        embedPath: "/embed/card/movie",
        permissions: [],
        triggers: ["imdb.com", "themoviedb.org"],
        embed_path: "/embed/card/movie",
        label: "Open in Cinema",
      },
      {
        id: "cinema-movie-viewed",
        kind: "timeline-card",
        placement: "timeline",
        name: "Movie viewed",
        description: "Movie detail page viewed",
        embedPath: "/embed/timeline/movie",
        permissions: ["timeline:write"],
        triggers: ["cinema-movie-viewed"],
      },
      {
        id: "cinema-tv-viewed",
        kind: "timeline-card",
        placement: "timeline",
        name: "TV show viewed",
        description: "TV show detail page viewed",
        embedPath: "/embed/timeline/movie",
        permissions: ["timeline:write"],
        triggers: ["cinema-tv-viewed"],
      },
      {
        id: "cinema-movie-watched",
        kind: "timeline-card",
        placement: "timeline",
        name: "Movie watched",
        description: "Movie marked as watched with optional rating",
        embedPath: "/embed/timeline/movie",
        permissions: ["timeline:write"],
        triggers: ["cinema-movie-watched"],
      },
      {
        id: "cinema-tv-watched",
        kind: "timeline-card",
        placement: "timeline",
        name: "TV show watched",
        description: "TV show marked as watched with optional rating",
        embedPath: "/embed/timeline/movie",
        permissions: ["timeline:write"],
        triggers: ["cinema-tv-watched"],
      },
      {
        id: "cinema-watchlist-add",
        kind: "timeline-card",
        placement: "timeline",
        name: "Added to watchlist",
        description: "Added to watchlist",
        embedPath: "/embed/timeline/movie",
        permissions: ["timeline:write"],
        triggers: ["cinema-watchlist-add"],
      },
      {
        id: "cinema-status-change",
        kind: "timeline-card",
        placement: "timeline",
        name: "Watching status changed",
        description: "Watching status changed",
        embedPath: "/embed/timeline/movie",
        permissions: ["timeline:write"],
        triggers: ["cinema-status-change"],
      },
      {
        id: "cinema-review",
        kind: "timeline-card",
        placement: "timeline",
        name: "Review posted",
        description: "Review posted",
        embedPath: "/embed/timeline/movie",
        permissions: ["timeline:write"],
        triggers: ["cinema-review"],
      },
      {
        id: "cinema-search",
        kind: "timeline-card",
        placement: "timeline",
        name: "Cinema search",
        description: "Cinema search performed",
        embedPath: "/embed/timeline/search",
        permissions: ["timeline:write"],
        triggers: ["cinema-search"],
      },
    ],
      internet: {
      proxy: [
        { host: "api.themoviedb.org", paths: ["/3/*"], methods: ["GET"], scope: "user" },
        { host: "image.tmdb.org", paths: ["/t/p/*"], methods: ["GET"], scope: "user" },
      ],
    },
    inter_app: {
      provides: [
        { type: "search", description: "Search user's watchlist items" },
        { type: "info-card", description: "Movie and TV info cards" },
      ],
    },
    settings: {
      schema: [
        {
          key: "tmdb_region",
          type: "select",
          label: "TMDB Region",
          default: "US",
          options: [
            { label: "United States", value: "US" },
            { label: "United Kingdom", value: "GB" },
            { label: "Germany", value: "DE" },
            { label: "France", value: "FR" },
            { label: "Spain", value: "ES" },
            { label: "Russia", value: "RU" },
          ],
        },
      ],
    },
  });
}
